# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(909, 255)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Atable = QtWidgets.QTableWidget(self.centralwidget)
        self.Atable.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Atable.setFont(font)
        self.Atable.setStyleSheet("background:rgb(255, 255, 255)")
        self.Atable.setObjectName("Atable")
        self.Atable.setColumnCount(0)
        self.Atable.setRowCount(0)
        self.gridLayout_3.addWidget(self.Atable, 2, 1, 1, 1)
        self.Ctable = QtWidgets.QTableWidget(self.centralwidget)
        self.Ctable.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Ctable.setFont(font)
        self.Ctable.setStyleSheet("background:rgb(255, 255, 255)")
        self.Ctable.setObjectName("Ctable")
        self.Ctable.setColumnCount(0)
        self.Ctable.setRowCount(0)
        self.gridLayout_3.addWidget(self.Ctable, 2, 4, 1, 1)
        self.Ntable = QtWidgets.QTableWidget(self.centralwidget)
        self.Ntable.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Ntable.setFont(font)
        self.Ntable.setStyleSheet("background:rgb(255, 255, 255)")
        self.Ntable.setObjectName("Ntable")
        self.Ntable.setColumnCount(0)
        self.Ntable.setRowCount(0)
        self.gridLayout_3.addWidget(self.Ntable, 2, 3, 1, 1)
        self.Etable = QtWidgets.QTableWidget(self.centralwidget)
        self.Etable.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Etable.setFont(font)
        self.Etable.setStyleSheet("background:rgb(255, 255, 255)")
        self.Etable.setObjectName("Etable")
        self.Etable.setColumnCount(0)
        self.Etable.setRowCount(0)
        self.gridLayout_3.addWidget(self.Etable, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 3, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.start_cam = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_cam.setFont(font)
        self.start_cam.setObjectName("start_cam")
        self.horizontalLayout_4.addWidget(self.start_cam)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 2, 1, 1)
        self.Otable = QtWidgets.QTableWidget(self.centralwidget)
        self.Otable.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Otable.setFont(font)
        self.Otable.setStyleSheet("background:rgb(255, 255, 255)")
        self.Otable.setObjectName("Otable")
        self.Otable.setColumnCount(0)
        self.Otable.setRowCount(0)
        self.gridLayout_3.addWidget(self.Otable, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Intelligent Mockup Interviewer"))
        self.label_5.setText(_translate("MainWindow", "Conscientiousness"))
        self.label_2.setText(_translate("MainWindow", "Agreeableness"))
        self.label.setText(_translate("MainWindow", "Openness"))
        self.label_3.setText(_translate("MainWindow", "Extraversion"))
        self.label_4.setText(_translate("MainWindow", "Neuroticism"))
        self.start_cam.setText(_translate("MainWindow", "Start"))

